global.name = ""
charmax = 6
nameforbidden = false
name_size = 1
name_y = 0
name_rot_off = 0
rotshake = 0.75
rotshake_delay = 4
toptext = ""
stage = 1
row = 0
column = 0
selected = ""
alphabetu = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]
alphabetl = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
lowoff = -60
xoff = array_create(array_length(alphabetu))
yoff = array_create(array_length(alphabetu))
timerval = 3
timer = timerval
shake = 0.3